name: Phoebus Release Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and publish
      env:
        GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy --batch-mode -Dmaven.wagon.http.pool=false -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}" --settings .github/maven/settings.xml --projects org.phoebus:parent,org.phoebus:service-alarm-logger,org.phoebus:app-alarm-model,org.phoebus:core-framework,org.phoebus:core-util
